// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASh_hBKRR2VZCfUrMCFg5YQrffSXHL6Qc',
    appId: '1:858873060169:web:664c87177ae92fa6a91898',
    messagingSenderId: '858873060169',
    projectId: 'crudflutter-68af8',
    authDomain: 'crudflutter-68af8.firebaseapp.com',
    storageBucket: 'crudflutter-68af8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7yuyionoFJJC3p_e0gJUj9_ka_6rl9s',
    appId: '1:858873060169:android:046e290ecf097a49a91898',
    messagingSenderId: '858873060169',
    projectId: 'crudflutter-68af8',
    storageBucket: 'crudflutter-68af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE55D809fcMutqIkinNnhuYk2stXufka0',
    appId: '1:858873060169:ios:f2603cfdb30b7859a91898',
    messagingSenderId: '858873060169',
    projectId: 'crudflutter-68af8',
    storageBucket: 'crudflutter-68af8.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE55D809fcMutqIkinNnhuYk2stXufka0',
    appId: '1:858873060169:ios:db71a4fc8c48b250a91898',
    messagingSenderId: '858873060169',
    projectId: 'crudflutter-68af8',
    storageBucket: 'crudflutter-68af8.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
